version: '1'
services:
  mongodb:
    image: mongo
    restart: always
    ports: 
    - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PW}
     - MONGO_INITDB_DATABASE=HaikuProject
    volumes:
      - mongo-data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env
volumes:
  mongo-data: 
   driver: local 